services:
  autostream:
    image: ghcr.io/l-zwlw/autostream:1.2.1
    container_name: autostream
    ports:
      - "7001:7001"
    environment:
      PORT: "7001"
      QBITTORRENT_URL: "http://qbittorrent:7002"
      DOWNLOADS_PATH: "/downloads"
      AUTOSTREAM_ADMIN_PASSWORD: "${AUTOSTREAM_ADMIN_PASSWORD:-}"
      ENABLE_EXPERIMENTAL_HTTP: "true"
      STREAM_ENGINE_URL: "http://stream-engine:7010"
    volumes:
      - ./data:/app/data
      - ./downloads:/downloads
    depends_on:
      - qbittorrent
      - stream-engine
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/l-zwlw/autostream-qbittorrent:1.2.1
    container_name: autostream-qbittorrent
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Amsterdam"
      WEBUI_PORT: "7002"
      TORRENTING_PORT: "6881"
    ports:
      - "127.0.0.1:7002:7002"
      - "6882:6881"
      - "6882:6881/udp"
    volumes:
      - ./qbittorrent:/config
      - ./downloads:/downloads
    restart: unless-stopped

  stream-engine:
    image: ghcr.io/l-zwlw/autostream-stream-engine:1.2.1
    container_name: autostream-stream-engine
    environment:
      ENGINE_DOWNLOADS_PATH: "/downloads/engine"
    ports:
      - "6883:6883"
      - "6883:6883/udp"
    volumes:
      - ./downloads:/downloads
    restart: unless-stopped
