services:
  autostream:
    image: ghcr.io/l-zwlw/autostream:nightly
    container_name: autostream
    ports:
      - "7001:7001"
    environment:
      PORT: "7001"
      QBITTORRENT_URL: "http://qbittorrent:7002"
      DOWNLOADS_PATH: "/downloads"
      STREAM_ENGINE_URL: "http://stream-engine:7010"
      ENABLE_EXPERIMENTAL_HTTP: "true"
      STREMIO_WEB_URL: "http://stremio-web:8080"
    volumes:
      - ./data:/app/data
      - ./downloads:/downloads
    depends_on:
      - qbittorrent
      - stream-engine
      - stremio-web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/l-zwlw/autostream-qbittorrent:nightly
    container_name: autostream-qbittorrent
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Amsterdam"
      WEBUI_PORT: "7002"
      TORRENTING_PORT: "6881"
    ports:
      - "127.0.0.1:7002:7002"
      - "6882:6881"
      - "6882:6881/udp"
    volumes:
      - ./qbittorrent:/config
      - ./downloads:/downloads
    restart: unless-stopped

  stream-engine:
    image: ghcr.io/l-zwlw/autostream-stream-engine:nightly
    container_name: autostream-stream-engine
    environment:
      ENGINE_DOWNLOADS_PATH: "/downloads/engine"
    ports:
      - "6883:6883"
      - "6883:6883/udp"
    volumes:
      - ./downloads:/downloads
    restart: unless-stopped

  stremio-web:
    image: tsaridas/stremio-docker:v1.3.8
    container_name: autostream-stremio-web
    environment:
      NO_CORS: "1"
      AUTO_SERVER_URL: "1"
    ports:
      - "7003:8080"
    volumes:
      - ./stremio-data:/root/.stremio-server
    restart: unless-stopped
    labels:
      io.autostream.component: "stremio-web-player"
